version: '3.8'

services:
  mariadb:
    container_name: maria
    build:
      context: ./
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - maria_data:/var/lib/mysql
    networks:
      - internal
volumes:
  maria_data:
    driver: local

networks:
  internal:
    driver: bridge
    