version: '3.8'

services:

  mariadb:
    container_name: maria
    build:
      context: ./mariadb
    env_file: .env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #   - MYSQL_DATABASE=${MYSQL_DATABASE}         # MariaDB crée cette base de données
    #   - MYSQL_USER=${MYSQL_USER}                 # MariaDB crée cet utilisateur
    #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}  
    volumes:
      - maria_data:/var/lib/mysql
    networks:
      - internal
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress
    # env_file: .env
    environment:
      WORDPRESS_DB_HOST: maria                  # L'hôte MariaDB est nommé "maria" dans Docker
      WORDPRESS_DB_USER: ${MYSQL_USER}          # Utilisateur pour se connecter à MariaDB
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}  # Mot de passe pour se connecter à MariaDB
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}      # Base de données à utiliser

    # entrypoint: >
    #   sh -c '      
    #   until mysql -h"maria" -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" -e "SELECT 1" >/dev/null 2>&1; do
    #     echo "Waiting for MariaDB...";
    #     sleep 5;
    #   done;
    #   if ! $(wp core is-installed --path=/var/www/html --allow-root); then
    #     wp core install --path=/var/www/html \
    #       --url="http://localhost" \
    #       --title="Mon Super Site" \
    #       --admin_user="admin" \
    #       --admin_password="mot_de_passe_admin" \
    #       --admin_email="admin@exemple.com" \
    #       --skip-email \
    #       --locale="fr_FR" --allow-root;
    #   fi;          
    #   wp user create dupont dupont@example.com --role=editor --user_pass=super_pass --allow-root;      
    #   php-fpm7.4 -F'   
    entrypoint: >
      sh -c '      
      until mysql -h"maria" -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" -e "SELECT 1" >/dev/null 2>&1; do
        echo "Waiting for MariaDB...";
        sleep 5;
      done;
      
      if ! wp core is-installed --path=/var/www/html --allow-root; then
        wp core install --path=/var/www/html \
          --url="https://svidot.42.fr" \
          --title="Mon Super Site" \
          --admin_user="admin" \
          --admin_password="mot_de_passe_admin" \
          --admin_email="admin@exemple.com" \
          --skip-email \
          --locale="fr_FR" --allow-root;
      else
        echo "WordPress is already installed.";
      fi
      
      if ! wp user get dupont --path=/var/www/html --allow-root >/dev/null 2>&1; then
        wp user create dupont dupont@example.com --role=editor --user_pass=super_pass --path=/var/www/html --allow-root;
      else
        echo "User dupont already exists.";
      fi

      php-fpm7.4 -F'   
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - internal
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:    
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html 
    networks:
      - internal
    depends_on:
      - wordpress
    restart: on-failure

volumes:
  wordpress_data:
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/svidot/data/wordpress_data'
  maria_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/svidot/data/maria_data'
  # maria_data:
  #   driver: local

networks:
  internal:
    driver: bridge
    