# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: seblin <seblin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/22 18:20:29 by seblin            #+#    #+#              #
#    Updated: 2024/09/22 18:20:31 by seblin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.8'

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD_FILE: ${MYSQL_ROOT_PASSWORD_FILE}
      MYSQL_PASSWORD_FILE: ${MYSQL_PASSWORD_FILE}
      MYSQL_USER_FILE: ${MYSQL_USER_FILE}   
    volumes:
      - maria_data:/var/lib/mysql
    networks:
      - internal
    restart: on-failure
    secrets:
      - db_root_password
      - db_password
      - db_user
 
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}                 
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

      WORDPRESS_DB_USER_FILE: ${MYSQL_USER_FILE}
      WORDPRESS_DB_PASSWORD_FILE: ${MYSQL_PASSWORD_FILE}

      WORDPRESS_ADM_USER_FILE: ${WORDPRESS_ADM_USER_FILE}
      WORDPRESS_ADM_PASSWORD_FILE: ${WORDPRESS_ADM_PASSWORD_FILE}

      WORDPRESS_USER_FILE: ${WORDPRESS_USER_FILE}
      WORDPRESS_PASSWORD_FILE: ${WORDPRESS_PASSWORD_FILE}    
    secrets:
      - db_user
      - db_password
      - wp_user
      - wp_password
      - wp_adm_user
      - wp_adm_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - internal
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    ports:    
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html 
    networks:
      - internal
    depends_on:
      - wordpress
    restart: on-failure

volumes:
  wordpress_data:
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/svidot/data/wordpress_data'
  maria_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/svidot/data/maria_data'

networks:
  internal:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password
  db_password:
    file: ../secrets/db_password
  db_user:
    file: ../secrets/db_user
  wp_user:
    file: ../secrets/wp_user
  wp_password:
    file: ../secrets/wp_password
  wp_adm_user:
    file: ../secrets/wp_adm_user
  wp_adm_password:
    file: ../secrets/wp_adm_password
    
# secrets:
#   db_root_password:
#     external: true
#   db_password:
#     external: true
#   db_user:
#     external: true
#   wp_user:
#     external: true
#   wp_password:
#     external: true
#   wp_adm_user:
#     external: true
#   wp_adm_password:
#     external: true