# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: seblin <seblin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/22 18:20:29 by seblin            #+#    #+#              #
#    Updated: 2024/09/22 18:20:31 by seblin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.8'

services:

  netdata:
    build: ./requirements/bonus/netdata
    ports:
      - "19999:19999"
    container_name: netdata
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    ports:
      - "6379:6379"
    networks:
      - internal
    volumes:
      - redis_data:/data
    restart: on-failure

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - internal
    restart: on-failure

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
    ports:
      - "21:21"
      - "40000-40005:40000-40005"
    volumes:
      - wordpress_data:/var/www/wordpress
      - ./requirements/nginx/conf/nginx.crt:/etc/ssl/ftp/nginx.crt
    networks:
      - internal     
    restart: always
    environment:
      FTP_USER_FILE: ${FTP_USER_FILE}
      FTP_PASSWORD_FILE: ${FTP_PASSWORD_FILE}
    secrets:
      - ng_key
      - ftp_user
      - ftp_password

  mariadb:
    container_name: mariadb  
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD_FILE: ${MYSQL_ROOT_PASSWORD_FILE}
      MYSQL_PASSWORD_FILE: ${MYSQL_PASSWORD_FILE}
      MYSQL_USER_FILE: ${MYSQL_USER_FILE}   
    volumes:
      - maria_data:/var/lib/mysql
    networks:
      - internal
    restart: on-failure
    secrets:
      - db_root_password
      - db_password
      - db_user

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}                 
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER_FILE: ${MYSQL_USER_FILE}
      WORDPRESS_DB_PASSWORD_FILE: ${MYSQL_PASSWORD_FILE}
      WORDPRESS_ADM_USER_FILE: ${WORDPRESS_ADM_USER_FILE}
      WORDPRESS_ADM_PASSWORD_FILE: ${WORDPRESS_ADM_PASSWORD_FILE}
      WORDPRESS_USER_FILE: ${WORDPRESS_USER_FILE}
      WORDPRESS_PASSWORD_FILE: ${WORDPRESS_PASSWORD_FILE}
      WORDPRESS_AUTH_KEY_FILE: ${WORDPRESS_AUTH_KEY_FILE}
      WORDPRESS_AUTH_SALT_FILE: ${WORDPRESS_AUTH_SALT_FILE}
      WORDPRESS_LOGGED_IN_KEY_FILE: ${WORDPRESS_LOGGED_IN_KEY_FILE}
      WORDPRESS_LOGGED_IN_SALT_FILE: ${WORDPRESS_LOGGED_IN_SALT_FILE}
      WORDPRESS_NONCE_KEY_FILE: ${WORDPRESS_NONCE_KEY_FILE}
      WORDPRESS_NONCE_SALT_FILE: ${WORDPRESS_NONCE_SALT_FILE}
      WORDPRESS_SECURE_AUTH_KEY_FILE: ${WORDPRESS_SECURE_AUTH_KEY_FILE}
      WORDPRESS_SECURE_AUTH_SALT_FILE: ${WORDPRESS_SECURE_AUTH_SALT_FILE}
      WORDPRESS_CACHE_HOST: redis
    secrets:
      - db_user
      - db_password
      - wp_user
      - wp_password
      - wp_adm_user
      - wp_adm_password
      - auth_key  
      - auth_salt
      - logged_in_key
      - logged_in_salt
      - nonce_key
      - nonce_salt
      - secure_auth_key
      - secure_auth_salt  
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - internal
    depends_on:
      - mariadb
    restart: on-failure
 
  nginx:
    container_name: nginx 
    build:
      context: ./requirements/nginx
    ports:    
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html   
      - ./requirements/nginx/conf/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./requirements/bonus/site:/var/www/site
    secrets:
      - ng_key 
    networks:
      - internal
    depends_on:
      - wordpress
    restart: on-failure

volumes:
  wordpress_data:
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/svidot/data/wordpress_data'
  maria_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/svidot/data/maria_data'
  redis_data:
    driver: local

networks:
  internal:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password
  db_password:
    file: ../secrets/db_password
  db_user:
    file: ../secrets/db_user
  wp_user:
    file: ../secrets/wp_user
  wp_password:
    file: ../secrets/wp_password
  wp_adm_user:
    file: ../secrets/wp_adm_user
  wp_adm_password:
    file: ../secrets/wp_adm_password
  ng_key:
    file: ../secrets/nginx.key
  auth_key:
    file: ../secrets/php_keys/auth_key 
  auth_salt:
    file: ../secrets/php_keys/auth_salt
  logged_in_key:
    file: ../secrets/php_keys/logged_in_key
  logged_in_salt:
    file: ../secrets/php_keys/logged_in_salt
  nonce_key:
    file: ../secrets/php_keys/nonce_key
  nonce_salt:
    file: ../secrets/php_keys/nonce_salt
  secure_auth_key:
    file: ../secrets/php_keys/secure_auth_key
  secure_auth_salt:
    file: ../secrets/php_keys/secure_auth_salt
  ftp_user:
    file: ../secrets/ftp_user
  ftp_password:
    file: ../secrets/ftp_password
